# 파이토치(Pytorch)란?

- Python 기반의 과학 연산 패키지
- Numpy를 대체하면서 GPU를 이용한 연산이 필요한 경우 사용
- 최대한의 유연성과 속도를 제공하는 딥러닝 연구 플랫폼이 필요한 경우 사용

## 파이토치의 장점

- 텐서플로우보다 간결
- 학습 및 추론 속도가 빠르고 다루기 간편
- Define-by-Run 프레임워크 ( 그레프를 만듦과 동시에 결과를 얻는 방식)
- 현재 대부분의 논문들이 파이토치로 구현

## 텐서 

- 파이토치의 기본 단위
- 다차원 배열을 처리하기 위한 데이터 구조
- Numpy의 ndarray와 거의 같은 API
- GPU를 사용한 계산 지원
- 어떤 데이터 형의 텐서이건 torch.tensor라는 함수로 작성가능

In [14]:
import torch
import numpy as np

# 빈 텐서 생성 
x = torch.empty(5,4)
print(x)
print('\n')

# 1로 구성된 텐서 생성
x = torch.ones(3,3)
print(x)
print('\n')

# 0
x = torch.zeros(3,4)
print(x)
print('\n')

# 랜덤 : 0~1 사이의 값
x = torch.rand(4,5)
print(x)
print('\n')

# 리스트나 narray를 텐서로 변환
test_list = [13,4]
test_array = np.array([4,56,7])

print(torch.tensor(test_list))
print(torch.tensor(test_array))
print('\n')

tensor([[5.7305e-36, 0.0000e+00, 7.0065e-44, 6.8664e-44],
        [6.3058e-44, 6.7262e-44, 7.0065e-44, 6.3058e-44],
        [6.7262e-44, 7.9874e-44, 1.1771e-43, 6.7262e-44],
        [7.0065e-44, 8.1275e-44, 7.4269e-44, 7.9874e-44],
        [8.1275e-44, 6.8664e-44, 7.0065e-44, 6.4460e-44]])


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


tensor([[0.2958, 0.7080, 0.2176, 0.4509, 0.9560],
        [0.2824, 0.8010, 0.5111, 0.9268, 0.3937],
        [0.2240, 0.5964, 0.6377, 0.9265, 0.9701],
        [0.7998, 0.4925, 0.1278, 0.7299, 0.2700]])


tensor([13,  4])
tensor([ 4, 56,  7])




In [17]:
# 텐서 사이즈 확인
print(x.size())
print('\n')

# 텐서 타입 확인
print(type(x))
print('\n')

torch.Size([4, 5])


<class 'torch.Tensor'>




In [22]:
# 텐서의 연산

x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
print('\n')

# x + y
print(x+y)
print('\n')

# add
print(torch.add(x,y))
print('\n')

# inplace방식으로 계산
y.add_(x)
print(y)

tensor([[0.8087, 0.3171],
        [0.6396, 0.3106]])
tensor([[0.5891, 0.4996],
        [0.2962, 0.3563]])


tensor([[1.3979, 0.8167],
        [0.9358, 0.6669]])


tensor([[1.3979, 0.8167],
        [0.9358, 0.6669]])


tensor([[1.3979, 0.8167],
        [0.9358, 0.6669]])


In [24]:
# 텐서 인덱싱
print(y[1,1])
print('\n')

# 텐서 슬라이싱
print(y[:,1])

tensor(0.6669)


tensor([0.8167, 0.6669])


In [26]:
# 텐서의 사이즈 바꾸기

x = torch.rand(8,8)
print(x)
print('\n')

print(x.view(64))
print('\n')
print(x.view(4,16))

tensor([[0.3487, 0.3575, 0.4847, 0.9052, 0.2279, 0.6034, 0.4974, 0.5475],
        [0.4993, 0.4907, 0.6133, 0.5663, 0.4486, 0.4693, 0.6496, 0.6598],
        [0.4178, 0.6947, 0.3229, 0.8201, 0.2608, 0.1922, 0.4853, 0.7810],
        [0.2317, 0.5408, 0.6536, 0.0906, 0.9341, 0.3201, 0.5394, 0.5509],
        [0.7466, 0.2707, 0.3026, 0.1574, 0.3495, 0.2146, 0.5739, 0.1103],
        [0.6924, 0.8051, 0.1066, 0.0313, 0.9462, 0.9980, 0.0551, 0.5202],
        [0.0394, 0.8831, 0.5208, 0.7259, 0.1764, 0.0737, 0.9949, 0.6653],
        [0.1198, 0.5194, 0.6154, 0.0136, 0.8595, 0.2858, 0.5473, 0.6124]])


tensor([0.3487, 0.3575, 0.4847, 0.9052, 0.2279, 0.6034, 0.4974, 0.5475, 0.4993,
        0.4907, 0.6133, 0.5663, 0.4486, 0.4693, 0.6496, 0.6598, 0.4178, 0.6947,
        0.3229, 0.8201, 0.2608, 0.1922, 0.4853, 0.7810, 0.2317, 0.5408, 0.6536,
        0.0906, 0.9341, 0.3201, 0.5394, 0.5509, 0.7466, 0.2707, 0.3026, 0.1574,
        0.3495, 0.2146, 0.5739, 0.1103, 0.6924, 0.8051, 0.1066, 0.0313, 0.9462,
     

In [31]:
# -1로 고정값을 정했을때 나머지를 자동으로 유추

x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # -1은 다른 차원에서 유추합니다.
test = x.view(-1,4)
print(x.size(), y.size(), z.size(),test.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8]) torch.Size([4, 4])


In [32]:
# 텐서를 ndarray로 변환

y = x.numpy()
print(y)
print(type(y))

[[-1.5358822   0.7801304  -1.2552966   0.97790164]
 [ 0.75771505  0.5387477  -1.1171709  -1.8452792 ]
 [ 0.55111295 -0.01050043 -1.6584823  -0.44969812]
 [ 1.3440101  -1.1015892   1.4265308   0.9339192 ]]
<class 'numpy.ndarray'>


In [33]:
# 원소가 한 개일때 원소의 값만 뽑아내고 싶을때

x = torch.ones(1)

x.item()

1.0